#!/usr/sbin/perl -w

# this script reads in sent-mail folder files of itrans and
# separates out in different mails

use strict;
my @words = {};
my $len;
my $name;

sub printFrom {
	my $from = shift;
	my $subject = shift || "(no subject)";
	@words = split(/\-/,$subject);
	$len = @words;
	if ($len == 2 ) {
		$name = $words[1];
		print "$len $name\n";
	}
}

my $filename = "set1.txt";

open (MAIL, "<$filename") or die "cant open : $!";

my $from;
my $subject;
my $header=1;

while (<MAIL>) {
	chomp;
	if (/^$/) {				# blank line ; this is not header
		undef $header;
		next;
	}
	if (/^From /) {		# beginning of header
		$header = 1;
		# printFrom ($from,$subject) if $from;
		$from = $subject = undef;
		next;
	}
	next unless $header;

	if (/^From: ([^<|(]*)[<|(]?([^>|)]*)[>|)]?/) { #parse From:
		my $s1 = $1;
		my $s2 = $2;
		$from = $s1 =~/@/? $s2: $s1;
		$from = $s1 unless $from;
		next;
	}
	if (/^Subject: (.*)$/) {
		$subject = $1;
		next;
	}
	print "------------------------------\n";
	printFrom ($from,$subject) if $from;
}

close MAIL;

