#!/usr/sbin/perl -w

# this script reads in sent-mail folder files of itrans and
# separates out in different mails

use lib '/u/yogeshk/Bin/Perl';

use strict;
use Mail::Header;
my $messagefile = "set1.txt";
open(MESSAGE,"$messagefile") or die "Unable to open $messagefile:$!\n";
my $header = new Mail::Header \*MESSAGE;
close(MESSAGE);
