

from nn_pmml_reader import NN_PMML_Reader
from tensorflow_pmml import Tensorflow_PMML

pmml = NN_PMML_Reader()
pmml.read_pmml('data/iris_for_tf.pmml') # generated by keras2pmml
pmml.print()

classifier = Tensorflow_PMML(pmml)
classifier.loadData()
model = classifier.trainModel()

model.print() # Do something with 'model' if needed.